# Bot hecho por sdeyy.lsd

# La id de tu servidor, si no sabes como obtenerla tienes problemas
GUILDID: "YOUR GUILD ID HERE"

# Nombre del bot
BOTNAME: "Tickets Bot"

# El color que tendran los embeds
EMBEDCOLOR: "PURPLE" # Tambien puede ser un HEX Color

# Token de tu bot, si no sabes como obtener en serio tienes problemas
TOKEN: "BOT TOKEN HERE"

# Tickets Configuration
TICKETS:
  TICKET_CATEGORY: "" # ID de la categoria donde se crearan los tickets
  SUPPORT_ROLE: "" # ID del rol de soporte (El que podra atender los tickets y claimearlos)
  ADMIN_ROLE: "" # ID del rol de administradores (No otorga permiso tampoco es necesario darle ninguno, solo no lo removera del ticket cuando sea claimeado y tendra permisos de enviar el panel de tickets)
  TICKET_CLOSE_TIME: "5000" # El tiempo que tardara en eliminarse el ticket (Tiempo en MS, 1000 = 1s, 5000 = 5s)
  TRANSCRIPT_CHANNEL: "" # ID del canal donde se enviara la transcripción del ticket

# Doy soporte por discord: sdeyy.lsd
# Servidor de discord: https://discord.gg/BWk7JxxcBg
